version: '2.1'

services:
  node:
    image: sharefiles
    build: .
    ports: 
      - 3000:3000
    volumes:
      - .:/home/shareFiles
    command: > 
      bash -c " ls && express --view=ejs  "
    stdin_open: true
    tty: true
    working_dir: /home/shareFiles

    
    
    
    
